/* global module */

module.exports.BOOK_NAMES = {
    bpf:     "Battle of the Pelennor Fields",
    fotn:    "Fall of the Necromancer",
    fotr:    "The Fellowship of the Ring",
    fotr_jb: "The Fellowship of the Ring (Journey Book)",
    fp:      "The Free Peoples",
    fr:      "Fallen Realms",
    gif:     "Gondor in Flames",
    harad:   "Harad",
    kd:      "Khazad-dûm",
    km:      "Kingdoms of Men",
    ma:      "Moria & Angmar",
    mordor:  "Mordor",
    roa:     "The Ruin of Arnor",
    rotk:    "The Return of the King",
    rotk_jb: "The Return of the King (Journey Book)",
    saf:     "Shadow & Flame",
    site:    "A Shadow in the East",
    sog:     "Siege of Gondor",
    sots:    "The Scouring of the Shire",
    ttt:     "The Two Towers",
    ttt_jb:  "The Two Towers (Journey Book)"
};

module.exports.FACTION_INFO = {
    angmar:        { name: "Angmar",        letter: "a" },
    arnor:         { name: "Arnor",         letter: "A" },
    dol_guldur:    { name: "Dol Guldur",    letter: "x" },
    dwarves:       { name: "Dwarves",       letter: "d" },
    easterlings:   { name: "Easterlings",   letter: "e" },
    fellowship:    { name: "Fellowship",    letter: "f" },
    free_peoples:  { name: "Free Peoples",  letter: "F" },
    gondor:        { name: "Gondor",        letter: "g" },
    harad:         { name: "Harad",         letter: "h" },
    isengard:      { name: "Isengard",      letter: "i" },
    lothlorien:    { name: "Lothlorien",    letter: "l" },
    mirkwood:      { name: "Mirkwood",      letter: "w" },
    moria:         { name: "Moria",         letter: "m" },
    mordor:        { name: "Mordor",        letter: "M" },
    numenor:       { name: "Numenor",       letter: "N" },
    rivendell:     { name: "Rivendell",     letter: "R" },
    rohan:         { name: "Rohan",         letter: "r" },
    shire:         { name: "The Shire",     letter: "s" },
    white_council: { name: "White Council", letter: "w" }
};

module.exports.LOCATIONS = {
    amon_hen:     "Amon Hen",
    arnor:        "Arnor",
    dol_guldur:   "Dol Guldur",
    eriador:      "Eriador",
    fangorn:      "Fangorn",
    fornost:      "Fornost",
    gondor:       "Gondor",
    harad:        "Harad",
    harondor:     "Harondor",
    helms_deep:   "Helm's Deep",
    isengard:     "Isengard",
    ithilien:     "Ithilien",
    lothlorien:   "Lothlorien",
    minas_morgul: "Minas Morgul",
    minas_tirith: "Minas Tirith",
    mirkwood:     "Mirkwood",
    mordor:       "Mordor",
    moria:        "Moria",
    morannon:     "Morannon",
    osgiliath:    "Osgiliath",
    rhovanion:    "Rhovanion",
    rhun:         "Rhûn",
    rohan:        "Rohan",
    the_shire:    "The Shire",
    weathertop:   "Weathertop"
}
