/* global module */

module.exports.BOOK_NAMES = {
    bot5a:   "The Battle of the Five Armies",
    bpf:     "The Battle of the Pelennor Fields",
    dos:     "Desolation of Smaug",
    fotn:    "The Fall of the Necromancer",
    fotr:    "The Fellowship of the Ring",
    fotr_jb: "The Fellowship of the Ring (Journey Book)",
    fp:      "The Free Peoples",
    fr:      "Fallen Realms",
    gif:     "Gondor in Flames",
    gt:      "Escape from Goblintown",
    harad:   "Harad",
    hobbit:  "The Hobbit: An Unexpected Journey",
    kd:      "Khazad-dûm",
    km:      "Kingdoms of Men",
    ma:      "Moria & Angmar",
    mordor:  "Mordor",
    roa:     "The Ruin of Arnor",
    rotk:    "The Return of the King",
    rotk_jb: "The Return of the King (Journey Book)",
    saf:     "Shadow & Flame",
    site:    "A Shadow in the East",
    sog:     "Siege of Gondor",
    sots:    "The Scouring of the Shire",
    tba:     "There and Back Again",
    ttt:     "The Two Towers",
    ttt_jb:  "The Two Towers (Journey Book)"
};

module.exports.FACTION_INFO = {
    angmar:          { name: "Angmar",                 letter: "a" },
    army_thror:      { name: "Army of Thror",          letter: "o" },
    arnor:           { name: "Arnor",                  letter: "A" },
    azogs_hunters:   { name: "Azog's Hunters",         letter: "z" },
    azogs_legion:    { name: "Azog's Legion",          letter: "Z" },
    dale:            { name: "Dale",                   letter: "q" },
    desolator_north: { name: "Desolator of the North", letter: "D" },
    dol_guldur:      { name: "Dol Guldur",             letter: "x" },
    dwarves:         { name: "Dwarves",                letter: "d" },
    easterlings:     { name: "Easterlings",            letter: "e" },
    fellowship:      { name: "Fellowship",             letter: "f" },
    free_peoples:    { name: "Free Peoples",           letter: "F" },
    goblintown:      { name: "Goblintown",             letter: "G" },
    gondor:          { name: "Gondor",                 letter: "g" },
    harad:           { name: "Harad",                  letter: "h" },
    iron_hills:      { name: "Iron Hills",             letter: "I" },
    isengard:        { name: "Isengard",               letter: "i" },
    laketown:        { name: "Lake-town",              letter: "L" },
    lothlorien:      { name: "Lothlorien",             letter: "l" },
    mirkwood:        { name: "Mirkwood",               letter: "w" },
    moria:           { name: "Moria",                  letter: "m" },
    mordor:          { name: "Mordor",                 letter: "M" },
    numenor:         { name: "Numenor",                letter: "N" },
    rivendell:       { name: "Rivendell",              letter: "R" },
    rohan:           { name: "Rohan",                  letter: "r" },
    shire:           { name: "The Shire",              letter: "s" },
    thorins_co:      { name: "Thorin's Company",       letter: "t" },
    trolls:          { name: "The Trolls",             letter: "T" },
    white_council:   { name: "White Council",          letter: "w" }
};

module.exports.ICON_STRINGS = {
    // Tab Icons
    account:   "\ue902",
    inventory: "\ue9dc",
    log_in:    "\ue969",
    log_out:   "\ue968",
    register:  "\ue969",
    scenarios: "\ue91f",

    // Resource Icons
    podcast:      "\uea27",
    video_replay: "\ue912",
    web_replay:   "\ue922"
}

module.exports.LOCATIONS = {
    amon_hen:     "Amon Hen",
    arnor:        "Arnor",
    dale:         "Dale",
    dol_guldur:   "Dol Guldur",
    erebor:       "Erebor",
    eriador:      "Eriador",
    fangorn:      "Fangorn",
    fornost:      "Fornost",
    goblintown:   "Goblintown",
    gondor:       "Gondor",
    harad:        "Harad",
    harondor:     "Harondor",
    helms_deep:   "Helm's Deep",
    isengard:     "Isengard",
    ithilien:     "Ithilien",
    laketown:     "Lake-town",
    lothlorien:   "Lothlorien",
    minas_morgul: "Minas Morgul",
    minas_tirith: "Minas Tirith",
    mirkwood:     "Mirkwood",
    mordor:       "Mordor",
    moria:        "Moria",
    morannon:     "Morannon",
    osgiliath:    "Osgiliath",
    rhovanion:    "Rhovanion",
    rhun:         "Rhûn",
    rohan:        "Rohan",
    the_shire:    "The Shire",
    weathertop:   "Weathertop"
}
